#!/bin/bash

# This script assumes that a file named "docker-compose.<foo>.yml" will extend the main docker compose file.
# files with "nolint" in the name will be passed over.

# improve legibility of output
printf "\n"

. ./scripts/styles

composefiles=$(find ./ ! -name '*nolint*' -type f -name "docker-compose*\.yml")
final_exit_code=0

for composefile in $composefiles; do
    unset out
    out=$(docker-compose -f docker-compose.yml -f "$composefile" config -q 2>&1); exit_code=$? 
    if [ ! $exit_code -eq 0 ]; then
        echo "$out"
        final_exit_code=$exit_code
    fi
done

if [ "$final_exit_code" -eq 0 ]; then
    printf "%sCompose config linted successfully!%s\n" "${GREEN}" "${NORMAL}"
else
    printf "\n%sdocker-compose failed linting!%s\n" "${RED}" "${NORMAL}"
fi

exit "$final_exit_code"
